### ISSUE TITLE
A confusing part in Readme

### ISSUE THREAD

**Issue by sierxue** [sillybun/vim-repl#1]
In README

> How to send code to REPL
In Normal Mode, press ww, code in the current line (including leading space and the end center) will be transmitted to REPL
In Visual Mode, press ww, selected code (whole line includeing leading space and the last center) will be trasmitted to REPL

In Normal Mode, when I press ww, the cursor just moves to right 2 words. Do I miss something?

**Comment by sillybun** [comment]
Thank you!
Actually, I have changed it to `<leader>w` because `ww` will destroy your experience in move using key w. Unfortunately, I forgot to change README in GitHub after I change it on Zhihu.
