### ISSUE TITLE
shift+v多行发送到python错误

### ISSUE THREAD

**Issue by thinkerhb** [sillybun/vim-repl#10]
Error detected while processing function repl#SendChunkLines[1]..repl#SendLines[12]..repl#GetPythonCode:
line    1:
E319: Sorry, the command is not available in this version: python3 << EOF
line    2:
E492: Not an editor command: import vim
line    4:
E492: Not an editor command: codes = vim.eval("a:lines")
line    5:
E492: Not an editor command: firstline = ''
line    6:
E492: Not an editor command: firstlineno = 0
line    7:
E121: Undefined variable: codes
E15: Invalid expression: codes:
line   11:
E488: Trailing characters:     else:
line   17:
E488: Trailing characters:     else:
line   25:
E488: Trailing characters: else:
line   37:
E488: Trailing characters:         else:
line   45:
E488: Trailing characters:                 else:
line   48:
E488: Trailing characters:                     else:
line   55:
E171: Missing :endif
Error detected while processing function repl#SendChunkLines[1]..repl#SendLines[12]..repl#RemoveExtraEmptyLine:
line    1:
E319: Sorry, the command is not available in this version: python3 << EOF
line    2:
E492: Not an editor command: import vim
line    4:
E492: Not an editor command: def GetBlockType(codeblock):
line    5:
E121: Undefined variable: not
E15: Invalid expression: not codeblock:
line   21:
E488: Trailing characters:     else:
line   35:
E488: Trailing characters:         else:
line   40:
E488: Trailing characters:     else:
line   66:

**Comment by misakisuna705** [comment]
我在mac下使用ipython多行直譯還是會出現上面的錯誤訊息

**Comment by sillybun** [comment]
原因是你的vim没有支持python3，你不妨在vim下输入：
`echo has('python3')`看看结果是否为1
