### ISSUE TITLE
how to disable "auto import"

### ISSUE THREAD

**Issue by pinggit** [sillybun/vim-repl#104]
this looks like a new issue that happened in recent version only.

when I start ipython repl, all of the modules that is present in current document will be executed.
a lot of the time this is not expected.

How can I disable this behavior?

when I start repl in a document (asciidoc), it scan the whole document and import all modules appearing in my document, which is NOT expected:
![image](https://user-images.githubusercontent.com/2038044/108008613-c1c82e80-6fce-11eb-9886-d0a270f04fe9.png)

**Comment by sillybun** [comment]
Sorry for the inconvenience!

just add
```
let g:repl_python_auto_import = 0
```
 in your vimdc

**Comment by pinggit** [comment]
it works. thanks!
