### ISSUE TITLE
最近有修改？ipdb用不了了，直接没有相关命令了。

### ISSUE THREAD

**Issue by yllr78** [sillybun/vim-repl#108]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**

 - result of `:REPLDebugInfo`

**Additional context**

**Comment by sillybun** [comment]
Let me check it

**Comment by sillybun** [comment]
在我的机器上是没有问题的，请在终端检查 python -m ipdb指令能否运行？

**Comment by yllr78** [comment]
![2021-03-14_151430](https://user-images.githubusercontent.com/20411331/111060462-082e8180-84d8-11eb-9035-d4b1cb0c8176.png)

**Comment by yllr78** [comment]
发现您更新了，但是还是没解决这个问题，请看截图。
![2021-03-18_115750](https://user-images.githubusercontent.com/20411331/111571209-5944bb00-87e1-11eb-8467-786e54e58097.png)

**Comment by sillybun** [comment]
真的很让我困惑，我是在`vim-repl/ftplugin/python/python-repl.vim` 下面定义这个命令的：

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/15951598/111577548-71bad280-87ed-11eb-8301-558f4026e534.png">

不应该出现找不到命令的情况，能看看你对应文件的110-115行么？

**Comment by yllr78** [comment]
主要问题是，我原来用的好好的，前段时间没有用，后来就发现这个问题了，下面是你需要的截图：
![Uploading 2021-03-18_115750.png…]()

**Comment by sillybun** [comment]
现在的问题是 `vim` 没有加载 `ftplugin` 中的文件，请尝试将 `ftplugin/python` 中的文件移动到 `plugin` 中。看看是不是能够解决这个问题。

**Comment by yllr78** [comment]
移过去以后命令有了，但是好像不能正常工作，一直报错：
In [27]: n
------------------------------------------------------------

NameError                  Traceback (most recent call last)

<ipython-input-27-ab0680a89434> in <module>
----> 1 n

NameError: name 'n' is not defined

**Comment by sillybun** [comment]
This was impossible. Please remove the plugin and then reinstall it.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/15951598/111940366-8b1f8f80-8b09-11eb-8fa2-d6af0462267a.png">

**Comment by yllr78** [comment]
工具帮助里的内容，应该是禁止了文件类型插件，就是这个变量为1，我的这个变量确实为1，默认应该不是1，但不知道是哪个插件给加上的。应该是有命令可以查到是哪个文件设置的吧？请教命令，谢谢。
let b:did_ftplugin = 1

**Comment by sillybun** [comment]
你的先看看你的 `vim-repl` 里面有没有 ftplugin 文件夹，按照道理应该是有的

**Comment by sillybun** [comment]
```
let b:did_ftplugin = 1
```
是防止文件类型插件二次加载的，我在文件里面加入了：

```
if !exists('g:REPLPythonLoaded')
    let g:REPLPythonLoaded = 1
else
    finish
endif
```
使用了 `g: REPLPythonLoaded`来防止多次加载同一个文件类型插件。
你可以 `:echo g:REPLPythonLoaded` 来看看是否这个值是1

**Comment by yllr78** [comment]
我重新卸载安装了这个插件，插件目录内ftplugin文件夹存在。
故障依旧，然后发现自己确实这个变量为1：let b:did_ftplugin = 1，所以怀疑是最近安装的哪个插件添加了这个变量，造成了问题。
:echo g:REPLPythonLoaded   这条命令显示未定义这个变量。   下面是我的插件目录截图：
![2021-03-23_144509](https://user-images.githubusercontent.com/20411331/112104603-6220fc80-8be6-11eb-91c2-a6fb3cc36da6.png)

**Comment by yllr78** [comment]
经过搜索，发现只有snippets.vim插件里有 let b:did_ftplugin = 1 这条语句，我该怎么做呢？

**Comment by yllr78** [comment]
经搜索vim下的文件内容发现：vim82\ftplugin\* 目录下的所有文件类型文件都有let b:did_ftplugin = 1这个赋值，自己安装的插件中只有coc下的snippets插件有，其他插件均无这个赋值定义。

**Comment by yllr78** [comment]
我原本打算把插件读取的顺序改一下，把vim-repl放在coc的前面应该能解决，但是我的设置是只有执行打开repl的命令才加载，这样的话，coc-snippets就先一步加载了，已经将那个变量设置导致无法导入ftplugin目录中的文件。
是否可以修改一下你的插件，执行了REPLToggle时候删除那个变量，等导入完成ftplugin目录中的文件后再加上那个变量，这样是否就能解决这个问题呢？  下面是我的插件配置，主要还是为了节省点内存空间，需要的时候再加载。
Plug 'sillybun/vim-repl', {'on': ['REPLToggle', 'REPLDebugStopAtCurrentLine']}

**Comment by yllr78** [comment]
我在解决完另一个插件问题后，vim-repl也好了，故障问题应该是原来vim安装到了d:\program files(x86)\vim目录下，目录带了空格，导致一些莫名其妙的问题。现在我把vim的安装目录调整到d:\tools目录下了，目录名没有空格，现在好多奇怪的问题都解决恶劣。最让我莫名其妙的是，原来是好的。

**Comment by sillybun** [comment]
hhhh，确实奇怪，路径错误真的是。。但是我一直没有调整过ftplugin 底下的东西，很久没有动过了。

**Comment by yllr78** [comment]
最近加入了telegram的中文vim讨论群，遇到了很多大牛，他们教我改目录解决，不然这问题不知道得困扰我多长时间。感谢作者的无私帮助，耽误了您不少时间 ：）

**Comment by sillybun** [comment]
这种问题完全没有想到过，因为我默认大家都是安装到 `$HOME/.vim/plugged`下面的
