### ISSUE TITLE
Send interrupt

### ISSUE THREAD

**Issue by dFenix7** [sillybun/vim-repl#11]
What should I do to interrupt python execution? 
If I type C-c while in the buffer running python, it moves to NORMAL mode, but it does not interrupt execution. Is there an alternative shortcut?

Thanks a lot in advance

**Comment by sillybun** [comment]
`<C-c>` works well to break execution in my computer. Can you provide:
1. your setting in vimrc relevated  to `vim-repl`
2. execution result of `REPLDebugInfo` command
