### ISSUE TITLE
Cannot get ipdb to work

### ISSUE THREAD

**Issue by flenzen** [sillybun/vim-repl#112]
**Describe the bug**
The readme page does not sufficiently explain how to get debugging using ipdb running. With how I understand the readme, I cannot get ipdb debugging to work.

**Samples**
The samples are taken using the following python code:
```
def gcd(a, b):
    if b == 0:
        return a
    return gcd(b,a%b)
print(gcd(60,48))
```
_Variant 1._ The cursor is placed in line 2. I open the ipython terminal using `:REPLToggle`. I see the ipython-prompt. With the python code active, I issue `:REPLDebugStopAtCurrentLine`. ipython receives the command `tbreak 2`, which fails:
```
In [1]: tbreak 2
  File "<ipython-input-1-32f0c35095e8>", line 1
    tbreak 2
           ^
SyntaxError: invalid syntax

In [2]: c
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-2b66fd261ee5> in <module>
----> 1 c

NameError: name 'c' is not defined
```
obviously, this code is intended for ipdb, which is installed.

_Variant 2_ I do the same, but without the ipython terminal open. When I issue `REPLDebugStopAtCurrentLine`, I get 
```
"ZYTREPL1 [führe aus]" [Verändert] --Keine Zeilen im Puffer--
"ZYTREPL1 [führe aus]" [Verändert] --Keine Zeilen im Puffer--
"ZYTREPL1 [führe aus]" [Verändert] --Keine Zeilen im Puffer--
```
(more lines appearing; it should translate as something like `"ZYTREPL1 [executing]" [changed] --No lines in buffer--`.

**Desktop (please complete the following information):**
vim: 8.2
python: 3.9.0
ipython: 7.19.0
ipdb3: 0.13.7

 - result of `:REPLDebugInfo`
```
VIM-REPL, last update: 2019.8.23
Operation System: Darwin
Support python3: 1
Support python: 0
has +terminal: 1
has +timers: 1
3.9.0 (default, Dec  6 2020, 18:02:34)
[Clang 12.0.0 (clang-1200.0.32.27)]
REPL program:
{'vim': 'vim -e', 'perl': ['/Users/lenzenf/.vim/bundle/vim-repl/ftplugin/perl/psh'], 'default': 'zsh', 'python': 'ipython'}
Fehler beim Ausführen von "function repl#REPLDebug":
Zeile   34:
E714: Liste benötigt

```

**Additional context**
relevant part of the vimrc:
```
noremap <C-r> :REPLToggle<cr>
let g:repl_program = {
            \   'python': 'ipython',
            \   'default': 'zsh',
            \   }
let g:repl_exit_commands = {
			\	'ipython': 'quit()',
			\	'python3': 'quit()'
			\ }
let g:repl_python_auto_send_unfinish_line = 1
let g:repl_cursor_down = 1
let g:repl_python_automerge = 1
let g:repl_python_auto_import = 1
let g:repl_ipython_version = '7.19'
autocmd Filetype python nnoremap <F12> <Esc>:REPLDebugStopAtCurrentLine<Cr>
autocmd Filetype python nnoremap <F10> <Esc>:REPLPDBN<Cr>
autocmd Filetype python nnoremap <F11> <Esc>:REPLPDBS<Cr>


```

**Comment by sillybun** [comment]
The reason is that you haven't install ipdb

install it via:

```
python -m pip install ipdb
```

Then use Variant 2

**Comment by flenzen** [comment]
I have ipdb installed. Since my default ipython runs python3, I have ipdb installed using ˋpython3 -m pip install ipdbˋ. Still, variant 2 is not working. Do you have a clue where my fault could lie instead?

**Comment by sillybun** [comment]
Can you check whether: `python -m ipdb` works or not?

**Comment by sillybun** [comment]
Update the plugin and check if it works.

**Comment by flenzen** [comment]
With python2 (which is my default python), it works. How can I configure vim-repl to work with ipdb3?

**Comment by sillybun** [comment]
I have update the plugin, you can configure it via:

```
    let g:repl_program = {
        \   'python': 'ipython',
        \   'python-debug': 'python3 -m ipdb',
        \   'default': 'zsh',
        \   'r': 'R',
        \   'lua': 'lua',
        \   'vim': 'vim -e',
        \   'snippets': 'ipython',
        \   }
```

**Comment by flenzen** [comment]
That helped, thank you very much for your quick help!
