### ISSUE TITLE
当使用F12断点DEBUG时出现问题！

### ISSUE THREAD

**Issue by TerryBLK** [sillybun/vim-repl#113]
我刚尝试使用vim编写python，安装插件后调用F12进行测试，发现出现错误。
![Snipaste_2021-04-18_10-32-53](https://user-images.githubusercontent.com/42261200/115132729-44a05080-a035-11eb-9f64-2800b168e615.png)

尝试使用:REPLDebugInfo调出错误日志，发现也出现错误。
![Snipaste_2021-04-18_10-43-44](https://user-images.githubusercontent.com/42261200/115132751-76191c00-a035-11eb-90ba-44448d2b09ed.png)

请问是我的操作有问题么?

**Comment by sillybun** [comment]
#112
