### ISSUE TITLE
Decorations as part of class or function definition

### ISSUE THREAD

**Issue by flenzen** [sillybun/vim-repl#114]
**Describe the bug**
Consider the python code
```
@decoration
class C:
   stuff
```
Assume first the cursor is in the first line.  When issuing `<leader>w`, only `@decoration` is to python, which waits for more input.  Issuing `<leader>w` again on the second line does not help; the waiting for input has to be cancelled using `^C` in the python session.

Assume now the cursor is in the second line. Issuing `<leader>w` only sends the class definition, but not the decoration line. Only selecting the class definition with the decoration in visual mode solves the problem.

**Desktop (please complete the following information):**

```
VIM-REPL, last update: 2019.8.23
Operation System: Darwin
Support python3: 1
Support python: 0
has +terminal: 1
has +timers: 1
3.9.0 (default, Dec  6 2020, 18:02:34)
[Clang 12.0.0 (clang-1200.0.32.27)]
REPL program:
{'vim': 'vim -e', 'perl': ['/Users/lenzenf/.vim/bundle/vim-repl/ftplugin/perl/psh'], 'python-debug': 'python3 -m ipdb', 'snippets': 'ipython', 'default': 'zsh', 'python': 'ipython'}
```

**Comment by sillybun** [comment]
This problem has been fixed. plz update the plugin to check if it works.

**Comment by flenzen** [comment]
Thanks, the update helped.
