### ISSUE TITLE
REPLToggle with key mapping requires extra key pressing

### ISSUE THREAD

**Issue by dr-costas** [sillybun/vim-repl#118]
**Describe the bug**
I have mapped the REPLToggle to a key mapping. When I'm executing the key mapping, REPL is not appearing immediately. Instead, I have to press an extra key for the REPL to appear. The extra key though is passed to REPL. 

Specifically, I have the following mapping: 

```vim
nnoremap <leader>r  :REPLToggle<CR>
```

When I, pressing `,r` (`,` is my `<leader>`), then nothing happens. If I press any other button afterward, e.g. I press `<CR>`, then the REPL appears and the `<CR>` is passed to REPL. 

I also have tried with the following mappings, but the result is the same: 

```vim
nnoremap <leader>r :call repl#REPLToggle()<CR>
```

**Desktop (please complete the following information):**

VIM-REPL, last update: 2019.8.23
Operation System: Darwin
Support python3: 1
Support python: 0
has +terminal: 1
has +timers: 1
3.7.9 (default, Aug 31 2020, 07:24:53)
[Clang 10.0.0 ]
['/opt/anaconda3/lib/python37.zip', '/opt/anaconda3/lib/python3.7', '/opt/anaconda3/lib/python3.7/lib-dynload', '/opt/anaconda3/lib/python3.7/site-packages', '_vim_path_']
REPL program:
{'vim': ['bash'], 'perl': ['~/.vim/plugged/vim-repl/ftplugin/perl/psh'], 'python-debug': 'python3 -m ipdb', 'default': ['bash'], 'python': ['ipython']}
REPL exit commands:
{'vim': 'q', 'zsh': 'exit', 'ptpython': 'quit()', 'lua': 'os.exit()', 'default': 'exit', 'bash': 'exit', 'R': 'q()', 'python': 'quit()', 'ipython': 'quit()'}
Current File Type: nerdtree
Current Type: bash
Current Exit Commands: exit

**Comment by sillybun** [comment]
what happened if you manually call the command `:REPLToggle` in normal mode?

**Comment by dr-costas** [comment]
Found the problem. There was another mapping using the `<leader>r`. I switched to a different mapping, `<leader>z`, and it works as it should be.
