### ISSUE TITLE
Open type or REPL independent of file type

### ISSUE THREAD

**Issue by dr-costas** [sillybun/vim-repl#119]
Hi, 

Thank you for this nice plugin! 

In my Vim setup, I need quite often to open a bash terminal while working with Python. If I use the standard `REPLToggle` command, then vim-repl opens an iPython console. Is there any way to specify which type of REPL to open? 

For example, something like `:REPLToggle('bash')` to open bash terminal, independent of the file type?

**Comment by sillybun** [comment]
`:REPLToggle bash` would work as your want

**Comment by dr-costas** [comment]
Got it! Thank you!
