### ISSUE TITLE
vim在view模式下选中执行多行代码报错

### ISSUE THREAD

**Issue by ZihaoXingstudy** [sillybun/vim-repl#14]
我在使用vim-repl的插件在view状态下选择多行后，发送执行时，不能执行，出现了下面的问题:
处理 function repl#SendChunkLines[1]..repl#SendLines[12]..repl#Sends 时发生错误:
第 10 行:
E117: 未定义的函数: AsyncCodeRun
请按 ENTER 或其它命令继续

请问该怎么解决啊？

**Comment by sillybun** [comment]
这是因为现在这个插件的异步功能被整合到[https://github.com/sillybun/vim-async](vim-async)中。

在vimrc中添加：`Plug 'sillybun/vim-async', {'do': './install.sh'}` ，然后执行PlugInstall

**Comment by ZihaoXingstudy** [comment]
恩恩，好的，谢谢作者！
