### ISSUE TITLE
请问vim-repl可以增加对perl脚本语言的支持吗？

### ISSUE THREAD

**Issue by ZihaoXingstudy** [sillybun/vim-repl#15]
请问您的vim-repl 可以添加对perl脚本语言的异步执行的支持吗，perl脚本语言跟python也是比较类似和十分重要的语言

**Comment by sillybun** [comment]
perl脚本支持是指那种支持？现在我觉得通过配置可以做到的有：
1. 编辑perl脚本的时候，按`<leader>r`可以打开交互式perl脚本环境
```
let g:repl_program = {
			\	"python": "python",
			\	"default": "bash"
			\	}
```
2. 使用`<leader>w`可以发送一行或者代码

还有什么需求？

**Comment by ZihaoXingstudy** [comment]
我按<learder>r后打开的是shell环境，不是perl交互式perl脚本环境

**Comment by sillybun** [comment]
你需要自己配置呀～这个插件的逻辑是，根据`g:repl_program`这个字典，打开`g:repl_program[filetype]`程序，所以你要确认perl脚本的filetype是什么～

```
let g:repl_program = {
			\	"python": "python",
			\	"default": "bash"
                         \       "perl": "perl -e"
			\	}
```

**Comment by ZihaoXingstudy** [comment]
我之前是这样设置的，好像不能一行一行执行perl脚本，您可以试一下．

**Comment by sillybun** [comment]
这是因为`perl`我没有找到很好的交互式环境，不过我现在写了一个简单的REPL实现，你只要更新应该就可以用了。

**Comment by sillybun** [comment]
![image](https://user-images.githubusercontent.com/15951598/57941977-e9bec580-7902-11e9-86c2-50919d9fe205.png)
现在我这边好像可以使用了。

**Comment by sillybun** [comment]
我对`perl`一点都不熟悉，所以你也可以自己写一个循环一直读取输入，然后输出结果。
