### ISSUE TITLE
<leader>w发送代码后，不能自动跳到下一行的代码，还是在最上面，这样不方便

### ISSUE THREAD

**Issue by ZihaoXingstudy** [sillybun/vim-repl#16]
<leader>w发送代码后，不能自动跳到下一行的代码，还是在最上面，这样不方便

**Comment by sillybun** [comment]
现在提供了开关`g:repl_cursor_down`，如果设成1的话，当选择多行代码发送后，便会跳转到下一行。

**Comment by ZihaoXingstudy** [comment]
我在.vimrc中设置了let  g:repl_cursor_down=1,但是选择多行代码发送后，光标还是在选中多行代码的第一行．

**Comment by sillybun** [comment]
你更新了么？
