### ISSUE TITLE
<leader>w in visual mode not working

### ISSUE THREAD

**Issue by stephenmm** [sillybun/vim-repl#18]
I can send single line commands to the Python REPL interpreter w/ <leader>w fine but when I do a visual selection it does nothing, no warning, no error, no output. Not sure how to debug this. Any help would be appreciated.

VIM 8.1

**Comment by sillybun** [comment]
Please update to the latest version and run command `REPLDebugInfo` and tell me the result.

**Comment by stephenmm** [comment]
Operation System: Linux
REPL program
{'perl': '/home/$USER/.vim/vide/plugged/vim-repl/ftplugin/perl/psh', 'default': 'bash', 'python': 'python'}
REPL exit commands
{'zsh': 'exit', 'ptpython': 'quit()', 'bash': 'exit', 'R': 'q()', 'python': 'quit()', 'default': 'exit'}
Current File Type:
python
Current Type:
python
Current Exit Commands
quit()
Use Build-in Async Engine

**Comment by sillybun** [comment]
Can you try to remove plugin `vim-async` and test if it OK

**Comment by stephenmm** [comment]
So in repl.vim::SendLines it is taking:

        elseif l:sn =~# 'python' || l:sn =~# 'python3'
            call repl#Sends(repl#RemoveExtraEmptyLine(repl#GetPythonCode(getline(l:firstline, a:last)), 'python'), ['>>>', '...', 'ipdb>', 'pdb>'])

Which goes to the repl.vim::repl#Sends and runs replforwin32 which does not seem to work for me.

but for the single line repl.vim::SendCurrentLine it is using:

		exe "call term_sendkeys('" . 'ZYTREPL' . ''', getline(".") . "\<Cr>")'
		exe "call term_wait('" . 'ZYTREPL' . ''',  50)'  

I temporarily hacked it by just having the SendLines always use "call term_sendkeys" and then it works...

It seems like maybe I do not async_engine and the script thinks that I do??? Not sure... But it is working for now... But very hacked...

**Comment by stephenmm** [comment]
I will close for now. If I get time I will try to dig into it a bit more and see if I can come up with a better fix that I might be able to share with you. Thanks for writing the plugin and for your assistance!
