### ISSUE TITLE
Buffer switching problem

### ISSUE THREAD

**Issue by pchhina** [sillybun/vim-repl#19]
Hi, 
Let me start by saying that this is a really cool project I tried today. Thanks for creating this. It seems very practical, however I cannot find a solution to a very common use case - how to switch between code buffers without switching to terminal buffer.

When I switch to another code buffer (:bnext, which I have mapped to tab), eventually it switches to terminal buffer. Once it is in terminal buffer, there is no way out of that! Then I have to exit out of terminal buffer to finally get my other code buffers.

Perhaps, there is already a solution/workaround that I do not know? If not, this will be a very powerful feature I think.

**Comment by pchhina** [comment]
Found a solution!
mapped <Tab> to <C-w>:bnext in terminal mode:

tnoremap <Tab> <C-w>:bnext<cr>

Thanks!

**Comment by pchhina** [comment]
Forgot that html sees less than as tag
I meant to say mapped Tab in terminal mode to Ctrl-w and then :bnext and then carriage return

**Comment by sillybun** [comment]
I'm happy to hear you have found a solution. I map 
```
tnoremap <C-h> <C-w><C-h>
tnoremap <C-j> <C-w><C-j>
tnoremap <C-k> <C-w><C-k>
tnoremap <C-l> <C-w><C-l>
```
to switch between buffers. I will try your solution. thank you!

**Comment by pchhina** [comment]
Hi Yiteng,

Thanks for reaching out and providing further pointers. This is helpful.

Regards,
Param

**Comment by williamlfang** [comment]
Thank you so much! 
For some who is facing this problem, it's just one line added into .vimrc:

tnoremap <Leader>n <C-w>:bnext<CR>
