### ISSUE TITLE
exit commands not set correctly

### ISSUE THREAD

**Issue by VincentZhou98** [sillybun/vim-repl#2]
When I run `REPLDebug`, the following log is showed:

```
REPL program
{'zsh': 'zsh', 'gnuplot': 'gnuplot', 'mma': 'MathematicaScript', 'matlab': 'matlab -nodesktop -nosplash', 'default': 'bash', 'python': '/Users/${USERNAME}/ana
conda3/bin/python', 'cpp.root': 'root -l'}
REPL exit commands
{'zsh': 'exit', 'bash': 'exit', 'default': 'exit', 'python': 'quit()'}
Current File Type:
python
Current Type:
/Users/${USERNAME}/anaconda3/bin/python
Current Exit Commands
exit                
```

replace  ${USERNAME} with my username

**Comment by sillybun** [comment]
The reason is that you have to specify your exit command explicitly. Because your `REPL` is `/Users/${USERNAME}/anaconda3/bin/python` for python file, you have to tell the plugin that the quit command for `/Users/${USERNAME}/anaconda3/bin/python` is `quit()`.
Therefore, you should put  `"/Users/${USERNAME}/anaconda3/bin/python": "quit()"` in the exit command dictionary.

**Comment by sillybun** [comment]
The reason is that you have to specify your exit command explicitly. Because your `REPL` is `/Users/${USERNAME}/anaconda3/bin/python` for python file, you have to tell the plugin that the quit command for `/Users/${USERNAME}/anaconda3/bin/python` is `quit()`.
Therefore, you should put  `"/Users/${USERNAME}/anaconda3/bin/python": "quit()"` in the exit command dictionary.

**Comment by VincentZhou98** [comment]
In fact I try it, but it still not works.

```
REPL program
{'zsh': 'zsh', 'gnuplot': 'gnuplot', 'mma': 'MathematicaScript', 'matlab': 'matlab -nodesktop -nosplash', 'default': 'bash', 'python': '/Users/${USERNAME}/ana
conda3/bin/python', 'cpp.root': 'root -l'}
REPL exit commands
{'zsh': 'exit', 'bash': 'exit', 'default': 'exit', 'python': 'quit()'}
Current File Type:
python
Current Type:
/Users/${USERNAME}/anaconda3/bin/python
Current Exit Commands
exit          
```

![image](https://user-images.githubusercontent.com/24786426/41466995-40cb1db8-70d7-11e8-8fa5-71faa7de9732.png)

**Comment by sillybun** [comment]
Really? Give me you `.vimrc` setting.

**Comment by VincentZhou98** [comment]
```
"------------------------------------------------------
"PERL vim 
nnoremap <leader>r :REPLToggle<Cr>
let g:sendtorepl_invoke_key = "<leader>w"
let g:repl_program = {
	\	"python": "/Users/${USERNAME}/anaconda3/bin/python",
	\	"gnuplot": "gnuplot",
	\	"matlab": "matlab -nodesktop -nosplash",
	\	"cpp.root": "root -l",
	\	"mma": "MathematicaScript",
	\	"zsh": "zsh",
	\	"default": "bash",
	\	}  
" root -l close splash window and work with stdin 
let g:repl_height = 15
let g:repl_width = 30
let g:repl_position = 3 
let g:repl_exit_command = {
			\	"/Users/${USERNAME}/anaconda3/bin/python": "exit()",
			\	"bash": "exit",
			\	"root": "exit(0)",
			\	"zsh": "exit",
			\	"default": "exit",
			\	}
"------------------------------------------------------

```

**Comment by sillybun** [comment]
oh, here we find the problem here. The exit command  dictionary is called `g:repl_exit_commands`, not `g:repl_exit_command`

**Comment by VincentZhou98** [comment]
Nice Plugin !!!

**Comment by sillybun** [comment]
Thanks for supporting.

**Comment by sillybun** [comment]
I think it's because I use `repl_prolem` (without s) and `repl_exit_command` (with s). Maybe I should change these two into the same form.

**Comment by sillybun** [comment]
I think it's because I use `repl_prolem` (without s) and `repl_exit_command` (with s). Maybe I should change these two into the same form.

**Comment by VincentZhou98** [comment]
Well, in fact I use the `commands` first. But when I find the `exit()` commands not works, I thought I  
must make a spelling mistakes. After changing it in the `.vimrc`, I just forget it.😅

**Comment by sillybun** [comment]
All right. Maybe I will let it be and wait for other guys to complaint about it.
