### ISSUE TITLE
您好，请问一下我在远程服务器上装的vim-repl插件不能发送多行代码

### ISSUE THREAD

**Issue by ZihaoXingstudy** [sillybun/vim-repl#20]
Error detected while processing function repl#SendChunkLines[1]..repl#SendLines[12]..repl#GetPythonCode:
line    1:
E319: Sorry, the command is not available in this version: python3 << EOF
line    2:
E492: Not an editor command: import vim
line    4:
E492: Not an editor command: codes = vim.eval("a:lines")
line    5:
E492: Not an editor command: firstline = ''
line    6:
E492: Not an editor command: firstlineno = 0
line    7:
E121: Undefined variable: codes
E15: Invalid expression: codes:
line   11:
E488: Trailing characters:     else:
line   17:
E488: Trailing characters:     else:
line   25:
E488: Trailing characters: else:
line   48:
E488: Trailing characters:                         #if codes[temp].startswith(
line   49:
E488: Trailing characters:                         #newlines.append(
line   51:
E488: Trailing characters:         else:
line   59:
E488: Trailing characters:                 else:
line   62:
E488: Trailing characters:                     else:
line   78:
E488: Trailing characters:                 #if codes[temp].startswith(
line   79:
E488: Trailing characters:                     #newlines.append(
line   82:
E488: Trailing characters: # print(newlines)
line   84:
E171: Missing :endif
Error detected while processing function repl#SendChunkLines[1]..repl#SendLines[12]..repl#RemoveExtraEmptyLine:
line    1:
E319: Sorry, the command is not available in this version: python3 << EOF
line    2:
E492: Not an editor command: import vim
line    4:
E492: Not an editor command: def GetBlockType(codeblock):
line    5:
E121: Undefined variable: not
E15: Invalid expression: not codeblock:
line   12:
E488: Trailing characters:         else:
line   24:
E488: Trailing characters:     else:
line   38:
E488: Trailing characters:         else:

**Comment by sillybun** [comment]
错误提示的很明白了，你的vim不支持python3
python3和python在vim上是不兼容的，所以你在vimrc的最开始加上：
```
if has('python3')
endif
```
 就好了

**Comment by ZihaoXingstudy** [comment]
这是我的vimrc的设置，我的python3是python3.7,发送多行代码还是出现上述的错误
48 ""设置vim-repl的快捷键
 49 if has('python3')
 50 endif
 51 let g:repl_program = {
 52             \   "python": "python3",
 53             \   "default": "bash",
 54             \   "perl": "perl",
 55             \   "r": 'R',
 56             \   }
 57 "将vim的leader前缀键设置成逗号，
 58 let mapleader=","
 59 "定义用leader前缀键+w来发送代码
 60 let g:sendtorepl_invoke_key = "<leader>w"
 61 nnoremap <leader>r :REPLToggle<Cr>
 62 autocmd Filetype python nnoremap <F12> <Esc>:REPLDebugStopAtCurrentLine<Cr>
 63 autocmd Filetype python nnoremap <F10> <Esc>:REPLPDBN<Cr>
 64 autocmd Filetype python nnoremap <F11> <Esc>:REPLPDBS<Cr>
 65 "let g:repl_position = 3
 66 let g:repl_cursor_down = 1
 67 tnoremap <C-h> <C-w><C-h>
 68 tnoremap <C-j> <C-w><C-j>
 69 tnoremap <C-k> <C-w><C-k>
 70 tnoremap <C-l> <C-w><C-l>

**Comment by sillybun** [comment]
字面意义上放到vimrc的第一行，你这在48行

**Comment by ZihaoXingstudy** [comment]
我又在第一行添加了，还是会报同样的错误啊 
 1 if has('python3')                                                                                                               
  2 endif
  3 set nocompatible
  4 syntax on
  5 set background=dark
  6 set backupcopy=yes
  7 set magic
  8 set hidden
  9 set guioptions-=T
 10 set guioptions-=m
 11 set smartindent
 12 set backspace=indent,eol,start
 13 set cmdheight=1
 14 set laststatus=2
 15 set number
 16 set cursorline

**Comment by sillybun** [comment]
你输入`vim --version`结果呢？
你更新一下，然后在vim中执行`REPLDebugInfo`命令，把结果放上来看看？

**Comment by ZihaoXingstudy** [comment]
这是vim --version的结果
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 11 2018 13:43:26)
Included patches: 1
Compiled by dna@dna.majorbio
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/mnt/ilustre/centos7users/dna/.env/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl  -lselinux -lacl -lattr -ldl

**Comment by ZihaoXingstudy** [comment]
Operation System: Linux
REPL program
{'r': 'R', 'perl': 'perl', 'default': 'bash', 'python': 'python3'}
REPL exit commands
{'zsh': 'exit', 'ptpython': 'quit()', 'lua': 'os.exit()', 'bash': 'exit', 'R': 'q()'
, 'python': 'quit()', 'default': 'exit'}
Current File Type:
python
Current Type:
python3
Current Exit Commands
quit()
Use Vim-Async Engine

**Comment by sillybun** [comment]
![image](https://user-images.githubusercontent.com/15951598/61614912-679ea480-ac97-11e9-8853-dd8da3abdb65.png)
你这个vim不支持python

**Comment by sillybun** [comment]
现在我针对不支持python的vim提供了一些有限的功能，可以正常使用原生的python，但是不适用与ipython和ptpython。
