### ISSUE TITLE
normal模式无法发送多行块（visual模式下可以）

### ISSUE THREAD

**Issue by skyblueee** [sillybun/vim-repl#22]
vim8.1  version -python +python3
visual模式下选中多行可以正确发送执行，但是normal模式定位在for循环第一行，只能发送第一行，很奇怪。
感觉应该是我自己配置的原因，和其他插件冲突了？想研究一下又没有太多时间，请问我该怎么排查这个问题？（去看那个函数？）如果有您的指点我应该会排查的高效一些。

**Comment by sillybun** [comment]
在vimrc中添加
```
let g:repl_auto_sends = ['class ', 'def ', 'for ', 'if ', 'while ']
```

**Comment by skyblueee** [comment]
原来需要特殊设置啊，README里没写啊。我觉得这个可以作为对Python的默认设置。
另外还有一个别的问题顺便请教一下：
我在vimrc里面设置了这两行：
au BufEnter *.h,*.c,*.cpp,*.py nmap <c-]> :YcmCompleter GoTo<cr>
au BufLeave *.h,*.c,*.cpp,*.py unmap <c-]>
我在打开py文件的时候映射也能正常工作。但是接下来在REPLToggle打开Python解释器程序的时候却报没有该映射。。。REPLToggle关闭的时候不会报错。

错误内容：
处理 BufLeave 自动命令 "*.py" 时发生错误:
E31: 没有这个映射
E31: 没有这个映射
E31: 没有这个映射
E31: 没有这个映射
E31: 没有这个映射
"ZYTREPL [running]" [已修改] --缓冲区无内容--

**Comment by skyblueee** [comment]
要设置成默认值的话，我建议针对不同的语言设置默认值。比如：
let g:repl_auto_sends = {'python': ['class ', 'def ', 'for ', 'if ', 'while '], 'perl': [...], 'octave': [...]}

**Comment by sillybun** [comment]
这个建议非常的中肯，我明天研究一下。还有一个比较关键的问题是我用这个插件是用来写`python`的，所以针对python、ipython等做了比较多的优化，我不知道其他还有什么语言对REPL的需求比较高。

**Comment by sillybun** [comment]
你这个错误好奇怪呀，不过你可以改成`au BufLeave .h,.c,.cpp,.py silent! unmap <c-]>`来不要显示这些恼人的错误。

**Comment by skyblueee** [comment]
如果其他语言不熟悉，可以留空让用户设置。不过我觉得设置关键字比较简单，看看语法设置上就好了，关键还在于对于不同程序不同的块判断会不太一样，比如MATLAB代码for是这样的：
for i = 1:10
    a = i + 1
end
后面有个end，也要一并发送。

我其实也主要是Python有需求，其他需求不大。其实就只做Python的REPL也不错，做一件事做精不才是Linux的哲学么;-)。

**Comment by sillybun** [comment]
还有你写的这个至少在我的版本的vim是不起仍和效果的，我这里需要改成：
```
au BufEnter *.h,*.c,*.cpp,*.py nmap <c-]> :YcmCompleter GoTo
au BufLeave *.h,*.c,*.cpp,*.py unmap <c-]>

```

**Comment by skyblueee** [comment]
> 还有你写的这个至少在我的版本的vim是不起效果的，我这里需要改成：
> 
> ```
> au BufEnter *.h,*.c,*.cpp,*.py nmap <c-]> :YcmCompleter GoTo
> au BufLeave *.h,*.c,*.cpp,*.py unmap <c-]>
> ```

github显示的问题，我确实是你那么设的：

> ```
> au BufEnter *.h,*.c,*.cpp,*.py nmap <c-]> :YcmCompleter GoTo<cr>
> au BufLeave *.h,*.c,*.cpp,*.py unmap <c-]>
> ```

silent这个建议不错，又学一招，虽然不治本，但解决了我的问题，谢谢。
