### ISSUE TITLE
发送代码块问题

### ISSUE THREAD

**Issue by caoshenghui** [sillybun/vim-repl#25]
**Describe the bug**
发送代码块会自动换行，怎么解决？

**Screenshots**
![image](https://user-images.githubusercontent.com/49725192/63930593-37aca300-ca86-11e9-972b-3ed962a37960.png)
![image](https://user-images.githubusercontent.com/49725192/63930611-4004de00-ca86-11e9-94dc-2bb7c8f528be.png)

**Comment by sillybun** [comment]
把`REPLDebugInfo`的结果和你关于vim-repl插件的配置都放上来

**Comment by sillybun** [comment]
按理说不应该出现这一个问题的

**Comment by caoshenghui** [comment]
![image](https://user-images.githubusercontent.com/49725192/63950007-d13b7b00-caad-11e9-9be8-19eebe3e5e1a.png)




我直接把vim配置文件给你吧，配置在161行，不知道是不是和其他配置冲突了，大概排查了一遍,好像其他配置没问题.

**Comment by caoshenghui** [comment]
![image](https://user-images.githubusercontent.com/49725192/63950673-05fc0200-caaf-11e9-9769-02b2eb2d2b1f.png)

**Comment by sillybun** [comment]
我明白了，我没有考虑到还有ipython3这种情况

**Comment by sillybun** [comment]
已经修复了

**Comment by caoshenghui** [comment]
好的，谢谢，这也太快了。
