### ISSUE TITLE
Can vim-repl support normal mode?

### ISSUE THREAD

**Issue by lightxue** [sillybun/vim-repl#26]
As title, Can vim-repl support normal mode?

In normal mode, I can easily do text operation what vim good at like finding key results, copying output...

Sorry if I'm mistaken, and thanks for your hard work!

**Comment by sillybun** [comment]
Most of the function of vim-repl works in visual mode, and some function work in normal mode.

Currently, press `<leader>w` in normal send current line to repl environment and also will send the whole block for `python`, such as:
```
<cursor>def func(a, b):
    return a+b
```
will send the whole function to REPL.

So, what kind of support do you suggest in normal mode? And which coding language do you use?

**Comment by lightxue** [comment]
Can the ZYTREPL buffer change to the normal mode? I found out it aways be in insert mode.

**Comment by sillybun** [comment]
`<c-w><c-n>`

**Comment by sillybun** [comment]
or you can use my mapping:
```
tnoremap <C-n> <C-w>N
tnoremap <ScrollWheelUp> <C-w>Nk
tnoremap <ScrollWheelDown> <C-w>Nj
```
you can press `<C-N>` to change to normal mode, or use scrollwhell to change to normal mode.

**Comment by lightxue** [comment]
It works!  `tnoremap <C-n> <C-w>N` is good. Thank you!
