### ISSUE TITLE
Debug python script using Logitech K380 keyboard

### ISSUE THREAD

**Issue by GuokaiLiu** [sillybun/vim-repl#27]
I have setted .vimrc as the following and I now using a Logitech K380 keyboard:

```
autocmd Filetype python nnoremap <F12> <Esc>:REPLDebugStopAtCurrentLine<Cr>
autocmd Filetype python nnoremap <F10> <Esc>:REPLPDBN<Cr>
autocmd Filetype python nnoremap <F11> <Esc>:REPLPDBS<Cr>
```

I prepared a file as test.py:
```
def test(a,b):
    c = a
    d = b
return c + d

test(1+2)
```

I set the cursot at test(1+2).
When I tried to use **fn+F10**, **fn+F11**, **fn+F12** to debug a python script, 
**fn + F10**: name 'n' is not defined
**fn + F11**: name 's' is not defined
**fn + F12**: name 'c' is not defined

Any suggestion?

Thank you very much!

**Comment by sillybun** [comment]
Can you provide the result of `REPLDebugInfo`

**Comment by sillybun** [comment]
You shouldn’t open REPL environment to use debug function. Just move the cursor (with REPL closed) to that line and press F10.

**Comment by GuokaiLiu** [comment]
VIM-REPL, last update: 2019.8.23
Operation System: Linux
Support python3: 0
Support python: 1
has +terminal: 1
has +timers: 1
2.7.5 (default, Apr 11 2018, 07:36:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
REPL program:
{'vim': 'vim -e', 'r': 'R', 'perl': '/home/dlliuguokai/.vim/bundle/vim-repl/ftplugin/perl/psh
', 'lua': 'lua', 'default': 'zsh', 'python': 'ipython'}
R for r is not executable.
zsh for default is not executable.
ipython version: 7.6.1
setted ipython version7
REPL exit commands:
{'vim': 'q', 'zsh': 'exit', 'ptpython': 'quit()', 'lua': 'os.exit()', 'default': 'exit', 'bas
h': 'exit', 'R': 'q()', 'python': 'quit()', 'ipython': 'quit()'}
Current File Type: python
Current Type: python -m ipdb %
Current Exit Commands: quit()




| |
刘国凯
|
|
邮箱：guokai_liu@163.com
|

签名由 网易邮箱大师 定制

On 09/14/2019 12:04, Yiteng Zhang. wrote:

Can you provide the result of REPLDebugInfo

**Comment by GuokaiLiu** [comment]
I use :REPLToggle to close REPL
And use :REPLDebugStopAtCurrentLine<Cr> instead of <F12> to test
However the result shown as the following popped out continuously.


Any suggestion?
Thank you very much!



"ZYTREPL [running]" [Modified] --No lines in buffer--

"ZYTREPL [running]" [Modified] --No lines in buffer--

On 09/14/2019 12:07，Yiteng Zhang.<notifications@github.com> wrote：

You shouldn’t open REPL environment to use debug function. Just move the cursor (with REPL closed) to that line and press F10.

**Comment by GuokaiLiu** [comment]
Sincerely thanks for your timely reply and help.
Finally, I found that I didn't `pip install ipdb` in my environment.
After `pip install ipdb`, I can follow your demo correctly.

It's a great job to help beginners like me for programming python scripts.
Thank you again for all your generous contribution. :  )

**Comment by sillybun** [comment]
I'm glad to hear that you have fix your problem. I will write it in README. Thank you!
