### ISSUE TITLE
Is it possible to make it run with a virtual environment? 

### ISSUE THREAD

**Issue by blasco** [sillybun/vim-repl#28]
I wonder what is the workflow to achieve this. Thank you very much for the advice.

**Comment by sillybun** [comment]
What's the meaning of "make it run with a virtual environment". I'm a little confused. Can you discribe what function do you want in detail?

**Comment by blasco** [comment]
I usually create virtual environment for different projects so I only install the required dependencies on each projects and so I can dump this dependencies into a requirements file. I create the virtual environments with the standard python module: 
```
python -m venv my_virtual_environment
```
This creates a bin, lib, src. In order to activate the environment one needs to source bin/activate generated file. This sets the python and pip paths to the environment folder among other things. So I n the terminal I can source this file but no in the REPL. Does it make sense what I'm saying? Thank you for the support.

**Comment by sillybun** [comment]
Maybe you can try `:REPLToggle python -m venv my_virtual_environment`. This will open REPL with command `python -m venv my_virtual_environment`.

**Comment by blasco** [comment]
I think that wont work. The `python -m vev` command is to create the environment. To activate I need to:
```
source /path_to_venv/bin/activate
```
Then it will work. So basically I need to source that before the python shell starts.

**Comment by sillybun** [comment]
Please provide all code you need to run in terminal to open python every time you want to run in virtual environment.

**Comment by blasco** [comment]
That's all. Creation of virtual environment, (not required by the plugin): 
```
python -m venv /path_to_new_venv
```
And to activate it, (We need that the plugin does this before calling python):
```
source /path_to_new_venv/bin/activate
```
Once we have sourced that file, we can do:
```
python
```
And will launch the python from the virtual env. 

If we do `pip install package`, it will be installed in the `path_to_new_venv/lib` folder. Everything is contained to the designated folder, which is very clean. If we want to go back to the system's python, we only need to type
 ```
deactivate
```
And done, now we can source the activate script of another venv or use the system one.

**Comment by sillybun** [comment]
I have updated the plugin which may solve your problem.

Currently, if you want to run python in virtual environment, you should put
`REPLENV: /path_to_new_venv/bin/activate` into python script like:

```
#REPLENV: ~/.PythonEnvironment/replenv/bin/activate

from sko.GA import GA
# todo
```

Then, every time you toggle `vim-repl`, it will open shell with order: `g:repl_program['default']' or 'bash' in macOS and Linux or 'cmd.exe' in Windows. And then it will run `source /path_to_new_venv/bin/activate` and then will open python program.

**Comment by blasco** [comment]
Great, thank you for the addition and for maintaining such a great plugin.

**Comment by blasco** [comment]
It would be really cool that these could be somehow configure in the vim configuration files. But as a bypass I guess it do the trick.

**Comment by sillybun** [comment]
Yes, I also think that writing it in python file doesn't look nice. I'm considering other possibilities. But the problem is that different python files maybe need different virtual environments (or no virtual env at all). So, I don't think that writing it in `.vimrc` is a good choice. Can you provide some suggestions?

**Comment by blasco** [comment]
If we could simply have a variable to store a pre-launch script I think it would work. If I could define:
```
let g:pyton_repl_pre_launch_command = "source /path_to_new_venv/bin/activate"
```
If that executes before the repl is launched, then we are all set. That's how I currently do it:
```
:terminal
source /path_to_new_venv/bin/activate
python
```

**Comment by sillybun** [comment]
I have added `g:repl_python_pre_launch_command` (I change the order of 'repl' and `python` for consistency) variable and you can try it.

Just put
```
let g:repl_python_pre_launch_command = "source /path_to_new_venv/bin/activate"
```
in vimrc and toggle repl environment.
