### ISSUE TITLE
请问一下能不能调试for循环内部的单行代码？在发送这行代码时候自动去掉缩进

### ISSUE THREAD

**Issue by ZihaoXingstudy** [sillybun/vim-repl#29]
python的缩进设计让Python的调试更加困难，不能向Ｒ语言一样能调节for循环或分支判断内部的单行代码，如果python的代码前面有缩进，单行调试的时候会报错．

请问作者在调试循环内部的单行代码的时候能不能自动去掉前面的缩进，变成没有缩进的代码，就可以执行了．

**Comment by sillybun** [comment]
能截一张单行调试出错的图片么？让我好理解什么意思。

**Comment by ZihaoXingstudy** [comment]
![for循环报错](https://user-images.githubusercontent.com/34788817/66397806-2eacdb00-ea0f-11e9-9e60-0681623bedae.png)

**Comment by ZihaoXingstudy** [comment]
我发送for循环内部第三行print(i)这行代码会报缩进错误，能不能在发送循环或判断内部有缩进的代码时，把缩进去掉，让这行代码直接对齐到最左边没有缩进后再发送？

**Comment by ZihaoXingstudy** [comment]
在循环次数很大，耗时很长的时候，我不希望一次调试整个for循环模块，我想直接先发送for循环里面的某些行代码，其它语言都可以，但是python会报缩进错误．

**Comment by ZihaoXingstudy** [comment]
能不能发送有缩进的python代码时，让这行代码直接去掉缩进，对齐到最左边再发送？

**Comment by sillybun** [comment]
现在有一种解决方式是shift+v选中一行或者多行，然后发送就可以了。你的提议我有时间会实现一下

**Comment by ZihaoXingstudy** [comment]
嗯嗯，好的，谢谢啊，这些就可以在交互式调试界面解决缩进报错的问题了．谢啦!  ^_^
大佬，你做的vim插件很好用，我很长时间都没用pycharm了，但是之前因为python的缩进报错问题感觉比其他语言调试起来有些不方便．

**Comment by ZihaoXingstudy** [comment]
我更新了一下vim-repl,现在可以直接发送执行前面有缩进的代码，也不会报缩进错误了，谢谢啊 ^_^
