### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by blasco** [sillybun/vim-repl#30]
Not sure how to help, but I started feeling a lower startup time of my vim. I run the following analysis:

vim --startuptime ~/vimstart.txt

And the slowest plugin by one order of magnitude was unfortunately vim-repl:

```
636.073  008.571: VimEnter autocommands
649.314  013.237: first screen update
087.969  013.598  008.244: sourcing /home/user/.vim/plugged/nerdtree/plugin/NERD_tree.vim
124.139  015.084  015.084: sourcing /home/user/.vim/plugged/vim-unimpaired/plugin/unimpaired.vim
023.657  022.524  012.355: sourcing /home/user/.vim/plug.vim
068.980  024.817  024.059: sourcing /home/user/.vim/plugged/colorv.vim/autoload/colorv.vim
558.770  025.608  025.579: sourcing /home/user/.vim/plugged/CSApprox/after/plugin/CSApprox.vim
070.913  027.011  002.194: sourcing /home/user/.vim/plugged/colorv.vim/plugin/colorv.vim
037.617  036.505  000.135: sourcing ~/.vim/vimrc
626.575  059.550: opening buffers
525.400  379.236  379.236: sourcing /home/user/.vim/plugged/vim-repl/plugin/default.vim
```

```
525.400  379.236  379.236: sourcing /home/user/.vim/plugged/vim-repl/plugin/default.vim
```
Not sure what might be causing the slow loading time, sorry for not being more helpful.

**Comment by sillybun** [comment]
I see. The possible reason is that vim REPL need to know the version of ipython. If ipython version isn’t written in vimrc, vimrepl will run command to check the version which is quite slow. Therefore you have better to tell repl the version of ipython.

**Comment by sillybun** [comment]
For those who use ipython as REPL program: Since ipython 7 and ipython 6 have a big difference, I have to treat them seperately and have to detect the version of ipython by ipython --version which will cause a obvious lagging. You have better to specify version of ipython by setting
```
let g:repl_ipython_version = '6'
```
or
```
let g:repl_ipython_version = '7.7'
```
