### ISSUE TITLE
debug进入ipdb之后无法再进入正常ipython环境

### ISSUE THREAD

**Issue by pinggit** [sillybun/vim-repl#31]
花了一天自习测了下，插件创意很好！
我遇到一个问题：进入ipdb断点调试之后，关掉ipdb，再调用REPLToggle打算进入常规ipython环境时，会再次调出刚才的ipdb环境。每次都如此。这是设计之中的还是bug？

**Comment by sillybun** [comment]
This problem has been fixed now. Please update and test it.
