### ISSUE TITLE
How to use python 3 as default environment for REPL

### ISSUE THREAD

**Issue by WangYuzhe** [sillybun/vim-repl#39]
I installed vim-repl on my ubuntu18.04 where both python 2 and python 3 are installed. The Vim is version 8. When I opened the REPL, the default environment was python 2. So how to change it to python 3? Thank you very much.

**Comment by sillybun** [comment]
Add:

```
let g:repl_program = {
            \   'python': 'python3',
            \   }
```

to vimrc.

**Comment by WangYuzhe** [comment]
Thank you very much.
