### ISSUE TITLE
vim-repl，设定当前行的断点，出现错误。。

### ISSUE THREAD

**Issue by hawkinchina** [sillybun/vim-repl#43]
问题，见标题
![image](https://user-images.githubusercontent.com/8294642/71064029-0aa50d00-21a9-11ea-8239-0e7ddd12808c.png)

**Comment by hawkinchina** [comment]
![image](https://user-images.githubusercontent.com/8294642/71064103-358f6100-21a9-11ea-90e7-943d85460d95.png)

**Comment by hawkinchina** [comment]
python：3.7.3
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 26 2019 21:43:33)
macOS version
包含补丁: 1-2350
编译者 Homebrew
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:

**Comment by sillybun** [comment]
现在REPL窗口和Debug公用一个窗口，所以需要先关闭REPL窗口，再设置断点运行。

我修改一下这个设定，把它们独立开。

**Comment by hawkinchina** [comment]
ok, 已经知道了。。 单步调试， 必须要关闭repl的解释器的窗口。。
谢谢。
