### ISSUE TITLE
IPython 4.2.1 IndentationError

### ISSUE THREAD

**Issue by pinggit** [sillybun/vim-repl#47]
我有个cygwin的环境，vim8，IPython 4.2.1 (Python 3.6.4)
报告缩进有问题：

比如：\w以下代码：

for i in range(len(scores)):
    print(scores[i])

报告：

In [4]: for i in range(len(scores)):
   ...: print(scores[i])

  File "<ipython-input-4-16707cb584bf>", line 2
    print(scores[i])
        ^
IndentationError: expected an indented block

If you want to paste code into IPython, try the %paste and %cpaste magic functio
ns.

同样的vimrc我在linux下测试没问题。IPython 7.8.0 Python 3.6.4

我没找到方法可以升级ipython， 请问这是不是已知的ipython版本过低造成的问题？

**Comment by sillybun** [comment]
我最低的测试版本是ipython 6以上，所以ipython 4是有问题。

更重要的问题是ipython 4和我的python 不兼容，所以我无法把我的ipython降级为4来进行测试。
