### ISSUE TITLE
<leader>w in visual mode not working when use ipython

### ISSUE THREAD

**Issue by ctrl2wei** [sillybun/vim-repl#5]
When use ipython as python repl, ipython will running in the termianl buffer and \<leader\>w was working well in normal mode, but in visual mode, it can not send code block to repl.

here is the setting
```
let g:repl_program = {
			\	"python": "ipython",
			\	"default": "bash"
			\	}

```

By the way, it came when enabled vim-repl
```
$ vim -V9vim.log
W22: Text found after :endfunction: }}}"Press ENTER or type command to continue
```

**Comment by sillybun** [comment]
This bug has been fixed. You can upgrade the plugin and test whether it works now. thx.
