### ISSUE TITLE
REPL隐藏之后无法显示

### ISSUE THREAD

**Issue by roachsinai** [sillybun/vim-repl#56]
**Describe the bug**

使用REPLHide隐藏buffer之后，无论是REPLToggle还是REPLUnhide均没有办法让RPL再显示。

** REPLDebug 结果**

```
处理 function <SNR>88_REPLDebugIPDB[6]..repl#REPLOpen 时发生错误:
第  121 行:
E95: 已有缓冲区使用该名称
```

**Comment by roachsinai** [comment]
但是如果REPLToggle打开REPL之后，再次REPLToggle，REPL环境会消失。但是下次再使用REPLToggle就是一个新的REPL环境了。

**Comment by sillybun** [comment]
很有可能是之前的更新时没有考虑这个功能，我看一下。

**Comment by sillybun** [comment]
问题已经解决，我个人觉得可能这是vim版本的问题。

**Comment by roachsinai** [comment]
嗯嗯，感谢！
