### ISSUE TITLE
Doesn't it better that REPLToggle never exit a repl env?

### ISSUE THREAD

**Issue by roachsinai** [sillybun/vim-repl#58]
Code form https://github.com/sillybun/vim-repl/blob/b19ad2473dbef030eaba0bb5981bc96a5f3593d0/autoload/repl.vim#L365

Saying that if there already a repl, `REPLToggle` will exit it.

I think REPLToggle should if repl visable, hide ti; if no repl create and show it; if repl is unvisable show it. It behave like convert to hide or unhide repl.

And another command exit the repl explicitly.

**Comment by roachsinai** [comment]
Now command REPLToggle may create, show, and exit a repl, it's a little confusion.

**Comment by roachsinai** [comment]
Add a small function in .vimrc:

```
function! REPLTOGGLE()
	if repl#REPLIsVisible()
		call repl#REPLHide()
    elseif repl#REPLIsHidden()
        call repl#REPLUnhide()
    else
        call repl#REPLToggle()
    endif
endfunction
nnoremap \r :call REPLTOGGLE()<Cr>
nnoremap \c :call REPLClose()<Cr>
```

**Comment by sillybun** [comment]
I just think using one key to open and close REPL is convenient. If there are two commands, one for open, one for close, users have to have two different noremap in `.vimrc`.

**Comment by roachsinai** [comment]
Yeah, just different thought about it, lol.
