### ISSUE TITLE
line continuation

### ISSUE THREAD

**Issue by mk0417** [sillybun/vim-repl#61]
Thanks for this good plugin.

Could you please check the problem as below:

- First example:
```
for i in range(5):
    a = i \
        + 1   # here is a tab in this line
    print(a)
```
The output is : 5
print(a) is executed after the loop is done.

- Second example:
```
for i in range(5):
    a = i \
    + 1  # no tab in this line
    print(a)
```
The output is:
1
2
3
4
5

The REPL can include print(a) in the loop.

Can you reproduce this? If not, this might be caused by my specific settings.

**Comment by sillybun** [comment]
Sorry, both cases looked fine on my machine. I use `ipython 7.8.0` for my python repl. What's yours? Can you provide the answer to `:REPLDebugInfo`?

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/15951598/80300747-da622080-87d1-11ea-9b98-17a27931b3af.png">

**Comment by mk0417** [comment]
Thanks, here is the info:

VIM-REPL, last update: 2019.8.23
Operation System: Darwin
Support python3: 1
Support python: 0
has +terminal: 1
has +timers: 1
3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)]
REPL program:
{'vim': 'vim -e', 'r': 'R', 'perl': '/Users/ma/.vim/plugged/vim-repl/ftplugin/perl/psh', 'lua': 'lua', 'default': 'zsh',
 'python': 'ipython'}
ipython version: 7.13.0
setted ipython version7.13
REPL exit commands:
{'vim': 'q', 'zsh': 'exit', 'ptpython': 'quit()', 'lua': 'os.exit()', 'default': 'exit', 'bash': 'exit', 'R': 'q()', 'py
thon': 'quit()', 'ipython': 'quit()'}
Current File Type: python
Current Type: ipython

**Comment by mk0417** [comment]
It has no problem after I resintall the plug.
