### ISSUE TITLE
Old config does not work

### ISSUE THREAD

**Issue by mk0417** [sillybun/vim-repl#63]
These configurations do not work after most recent updates and the error message suggests using list:
```
let g:repl_program = {
            \   'python': 'ipython',
            \   'default': 'zsh',
            \   'r': 'R',
            \   'lua': 'lua',
            \   'vim': 'vim -e',
            \   }
```

Using list solves the problem:
```
let g:repl_program = {
            \   'python': ['ipython','python'],
            \   'default': ['zsh'],
            \   'r': ['R'],
            \   'lua': ['lua'],
            \   'vim': ['vim -e']
            \   }
```

**Comment by sillybun** [comment]
This update is contributed by @roachsinai. Thanks for his/her great work. However, I think support both the string and list configuration is a better choice.

**Comment by sillybun** [comment]
I have fixed the problem. Now you can write it both in list version or string version.
