### ISSUE TITLE
请问在调试时因为中文字符编码导致调试错误怎么办

### ISSUE THREAD

**Issue by mlx123** [sillybun/vim-repl#66]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28173246/80858242-bf3c5880-8c8a-11ea-8350-82d28ed63bdc.png)

**Screenshots**

**Desktop (please complete the following information):**

 - result of `:REPLDebugInfo`

**Additional context**
在没有中文编码的环境下可以正常使用

**Comment by sillybun** [comment]
这是pdb或者ipdb的问题。
