### ISSUE TITLE
Debug issue and error shows in repl#REPLDebug (using pyenv)

### ISSUE THREAD

**Issue by tllinhank** [sillybun/vim-repl#67]
Hi there,
I tried to use debug function referred in readme. Vim showed exactly the same as [#27 ](https://github.com/sillybun/vim-repl/issues/27) . But I'm pretty sure I have ipdb installed in the python version. So I used `REPLDebugInfo` to check problem. The result also showed the error as [#65 ](https://github.com/sillybun/vim-repl/issues/65) . But I don't understand the answer that you answered because there is a `python2` and a `python3` installed in my `~/bin`. By the way, I use pyenv to manage my python versions and all my python are installed by pyenv except the system one. So, do you have any idea?

Thank you guys. This is a excellent plugin.

My system information:
OS: Ubuntut 20.04
Vim: Vim 8.1
shell: bash
python version:
  3.8.2(system)
  2.7.18rc1(system)
  3.6.8(pyenv)(global)

My `.vimrc`:

![Screenshot from 2020-05-02 16-35-07](https://user-images.githubusercontent.com/59074313/80859380-04fd1f00-8c93-11ea-922c-1b9bde9b4fa1.png)

Issues:
![Screenshot from 2020-05-02 16-37-23](https://user-images.githubusercontent.com/59074313/80859454-ce73d400-8c93-11ea-9d8a-23e59e4d88c0.png)

![Screenshot from 2020-05-02 16-37-55](https://user-images.githubusercontent.com/59074313/80859435-9ff5f900-8c93-11ea-8311-2fde0a5ded98.png)

**Comment by tllinhank** [comment]
I guess the problem cause by missing package. Maybe you can let me know what packages that you used for the plug.

**Comment by sillybun** [comment]
What you open is `python` not `ipdb`

**Comment by sillybun** [comment]
You can add
```
autocmd Filetype python nnoremap <F12> <Esc>:REPLDebugStopAtCurrentLine<Cr>
autocmd Filetype python nnoremap <F10> <Esc>:REPLPDBN<Cr>
autocmd Filetype python nnoremap <F11> <Esc>:REPLPDBS<Cr>
```
to your .vimrc and press `<F12>` to have another try.

**Comment by sillybun** [comment]
debug windows can only be opened when REPL windows is closed.

**Comment by tllinhank** [comment]
I think I know what is going on. I should open ipython instead python in the console.
