### ISSUE TITLE
Windows下可视模式选中多行代码执行报错

### ISSUE THREAD

**Issue by xshuai1006** [sillybun/vim-repl#7]
可视模式下选中多行代码后按<leader>w到REPL中执行报错（单行执行正常）：

> 处理 function repl#SendChunkLines[1]..repl#SendLines[12]..repl#GetPythonCode 时发生错误：

> E370: 无法加载库 python36.dll

> E263: 抱歉，此命令不可用，无法加载 Python 库
![default](https://user-images.githubusercontent.com/1651111/44946738-85bba600-ae34-11e8-844e-93b94b9d09a9.png)

环境：
1. 操作系统：Windows 10 家庭版 x64 1803；
2. Vim版本：8.1，32位；
3. python版本：3.5.4，32位。

**Comment by xshuai1006** [comment]
可视模式下选中多行代码后按<leader>w到REPL中执行报错：

> 处理 function repl#SendChunkLines[1]..repl#SendLines[12]..repl#GetPythonCode 时发生错误：

> E370: 无法加载库 python36.dll

> E263: 抱歉，此命令不可用，无法加载 Python 库
![default](https://user-images.githubusercontent.com/1651111/44946738-85bba600-ae34-11e8-844e-93b94b9d09a9.png)

**Comment by luyuhao98** [comment]
+1

**Comment by sillybun** [comment]
@xshuai1006 @luyuhao98 Now this plugin support Windows! Enjoy it!
