### ISSUE TITLE
A little automation: An improvement or feature request

### ISSUE THREAD

**Issue by yelled1** [sillybun/vim-repl#70]
Is there a simple way to check for REPLIsVisible = 0 then open up repl = REPLToggle then execute the line or chunk of the code & REPLIsVisible = 1 then just execute the code into repl?
This is likely a minor update, but would make it much more robust, as this is done in iron_vim or emacs.
Usually, I can giggle with existing code, but I don't see a straight way to do this.
It's a well executed plugin & code & this is only thing I miss for now.  
Thank you,

**Comment by sillybun** [comment]
I will fix it and provide an option.

**Comment by yelled1** [comment]
Thank you - this would make it more robust!

**Comment by sillybun** [comment]
Set `let g:repl_unhide_when_send_lines = 1` will do the work.
