### ISSUE TITLE
Format code?

### ISSUE THREAD

**Issue by yelled1** [sillybun/vim-repl#74]
Hi:

I am NOT sure which key combination I have used, but when I was attempting to format a very long line by hand, magically the entire line was formatted as below.
```
return jaydebeapi.connect(jclassname,
                          driver_args,
                          jars=jars,
                          libs=libs)
```
Above used to be a one line.
Is this one of the feature of vim-repl? If so, how do I activate it?
Only other two python specific plugins are:
 - https://github.com/vim-scripts/indentpython.vim.git   
 - https://github.com/nvie/vim-flake8.git
Thank you much,

**Comment by sillybun** [comment]
I add a configuration:
```
let g:autoformatpython_break_long_lines = 0
```

If this value is set to 1, a very long line will be broken into several shorter lines. If it is set to 0, then long lines will still be a line.

**Comment by sillybun** [comment]
This is not the feature of `vim-repl`. This is a feature of
https://github.com/sillybun/autoformatpythonstatement

**Comment by yelled1** [comment]
Thanks - I will try to reinstall autoformat.
