### ISSUE TITLE
If I move into REPL & come back the line does NOT execute until I change to insert mode & hit return

### ISSUE THREAD

**Issue by yelled1** [sillybun/vim-repl#76]
**Describe the bug**
When executing: If I move into REPL  to examine the result & come back into the editor the line does NOT execute until I go back into the REPL & change to insert mode & hit return

I have following in \.vimrc to move between windows
```
noremap <c-x>o <c-w>w
inoremap <c-x>o <c-o><c-w>w
tnoremap <c-x>o <c-\><c-n><c-w><c-w>
```
In Editor let's say I have;
```
import sys  (I hit ,r to REPLToggle &  ,w to execute in the REPL, then I move to repl by <c-x>o then manipulate some variable like look at sys.path inside REPL )
```
![image](https://user-images.githubusercontent.com/2314710/82106022-88375f80-96ec-11ea-8928-780c37886425.png)
Now I come back to editor to get following line sent to REPL
```
from os.path import join, dirname, realpath, abspath, exists  (I hit ,w to execute in the REPL)
```
REPL does not how any lines, until I hit <c-x>o to go back to repl & hit 'a' to put back in insert mode.
Only problem after that is that I have to keep on going back to REPL to get any execution.

Obviously, when I just put the REPL in command or normal mode
![image](https://user-images.githubusercontent.com/2314710/82106132-2d523800-96ed-11ea-91c1-dccc2e2a2282.png)
and when I hit 'a' the line appears on the REPL:
![image](https://user-images.githubusercontent.com/2314710/82106145-3e9b4480-96ed-11ea-9d0c-b8591ac649da.png)
Is there a simple way to leave the REPL not in NORMAL mode & come back up to the editor?
This bug is annoying & may be it's just matter of adjusting the maps above.
Thanks much,

**Comment by sillybun** [comment]
Why not use:
```
tnoremap <c-x>o <C-w>w
```

**Comment by sillybun** [comment]
I think that leaving REPL environment which is in insert mode should not change the mode of REPL environment.

**Comment by yelled1** [comment]
Yep that does the job. Silly me. Thank you for all your help.
