### ISSUE TITLE
custom exit command ignored for filetype other than python

### ISSUE THREAD

**Issue by linusboyle** [sillybun/vim-repl#8]
this plugin cannot identify custom exit command,although setting python and default command is possible.It cannot distinguish other filetypes and keeps using the default `exit`

my configuration is as follows:
>let g:repl_exit_commands = {
			\	"python": "quit()",
            \   "javascript":'.exit',
            \   "cpp":".q",
			\	"bash": "exit",
			\	"zsh": "exit",
			\	"default": "exit",
			\	}

Vim8.1 Huge build with gui,BTW

**Comment by sillybun** [comment]
Maybe you have some misunderstandings about the exit commands. Exit commands are determined by the program run in terminal, not the filetypes. For example, you want to run `python` when writing a python script, so you have to type `quit()` to quit the program. I have no idea what do you want to open in the terminal when you write c++ code. I think there is no program with name "cpp".

**Comment by linusboyle** [comment]
> Maybe you have some misunderstandings about the exit commands. Exit commands are determined by the program run in terminal, not the filetypes. For example, you want to run `python` when writing a python script, so you have to type `quit()` to quit the program. I have no idea what do you want to open in the terminal when you write c++ code. I think there is no program with name "cpp".

@sillybun 
OK,I get it. Now it works well,after changed to this:
```vim
let g:repl_exit_commands = {
			\	"python": "quit()",
                        \       "node":'.exit',
                        \       "cling":".q",
			\	"bash": "exit",
			\	"zsh": "exit",
			\	"default": "exit",
			\	}
```

I think the problem here is that not only interpretive language has REPL tools and usually the name of the filetype and interpreter program of an interpretive language is the same.But it's not the case when it comes to cplusplus .etc.Maybe a note in Readme is needed.

Best Regards.
