### ISSUE TITLE
How to Run vim-repl when I don't have bash?

### ISSUE THREAD

**Issue by suliveevil** [sillybun/vim-repl#80]
I'm using iVim on iPadOS, which has a terminal named `ivish`.
How to Run vim-repl when I don't have bash?

**Comment by sillybun** [comment]
Emmm, interesting idea, and I have thought about it. But there is no command line software available on `ivish` like Python. What's the meaning of using vim-repl then?

**Comment by suliveevil** [comment]
I do have python3 in ivish, it's equivalent to python in bash on PC.

**Comment by sillybun** [comment]
That's impressive. So, can you install vim-repl for iVim? Does it have a plugin manager?

**Comment by suliveevil** [comment]
Yes, Vim8's builtin package management and iVim's `iplug`.
You can even just create the `~/.vim/plugin`  and put scripts in it.

System vimrc:
```viml
" set default shell
set shell=ivish 
```

**Comment by sillybun** [comment]
You can just install vim-repl and using the setting:

```
let g:repl_program = {
            \   'python': 'python3',
            \   'default': 'ivish',
            \   }
```

But there are some bug for python code which costs time to fix.

**Comment by suliveevil** [comment]
Thank you very much, that works!

Somehow iVim's IPython environment have bugs, I'm using Python's PDB.

![pdb](https://user-images.githubusercontent.com/35763237/84561433-e7859f80-ad7e-11ea-8242-cd57146f9431.jpeg)
