### ISSUE TITLE
Write REPL output to clipboard or directly into buffer(commented)

### ISSUE THREAD

**Issue by suliveevil** [sillybun/vim-repl#81]
Like JupyterNotebook.

**Comment by yelled1** [comment]
May be I am understanding this, but NOT sure you need to get this functionality via plugin.
Writing to clipboard or buffer requires you to deal with whichever os your working with:
I have below plus pbcopy plugin added:
```
 93 "___ keyMaps for copy __________________________________________________
 94 "apt install xclip
 95 vmap "+y :!xclip -sel c
 96 map "+p :r!xclip -o -sel c
 97 vnoremap <C-c> "+y
 98 set clipboard=unnamed " For mac yy <D-p> did not work for neovim
 99 vmap <leader>yy :!pbcopy -sel c
100 ":!unnamed -sel c
```
Depending on your os you may have 3 different clipboards (which you can read about from pbcopy):
this is why sometimes "*p" or "ctrl-p" or "+p" works at different instances & OS.
Just add your favorite xterm emulator into the picture or across OS into the picture & you got a hella of mess.
Suggesting:
1st, read up on the different clipboard
2nd, see if pbcopy helps
3rd, you really need to tell the developer which OS, which emulator, & vim version before asking for a change. One lines won't likely cut it.

**Comment by suliveevil** [comment]
Outside clipboard is not what I mean.
I just want Vim to catch the content in terminal.
So we can save the content by Vim, without outside specific environment or special tools.

**Comment by sillybun** [comment]
Good idea. I will accomplish it in few weeks.

**Comment by suliveevil** [comment]
That would be great!

In cmdline mode,we can redir output to file or register, or using https://github.com/at-cf/vim-redir-output redir output to buffer.

In terminal mode, we now don't have a general way.

**Comment by sillybun** [comment]
This function has been completed. But, I only support ipython now.

You can add

```
let g:repl_output_copy_to_register = "t"
```

to your vimrc, in which `"t"` means the name of the register. Then output of python code will be copy to this register automatically.

**Comment by suliveevil** [comment]
That is awesome.
Let me guess, t means "transfer"?

**Comment by sillybun** [comment]
lol. it also mean "terminal". Of course, you can choose your favorite register and paste the content with `"tp`

**Comment by suliveevil** [comment]
I like that! I won't change the defaut config only if had to.

With repl and register, we got something like jupyter, and it has less dependencies , this is awesome!

**Comment by Neryfoot** [comment]
Hey, 

I couldn't get this to work, i copied your user config for vim-repl just make sure I wasn't messing up something.

My "t" register is always empty after running commands or scripts. Any idea what could be the problem?

**Comment by sillybun** [comment]
Currently, only ipython is supported. Do you use some other repl program?

**Comment by Neryfoot** [comment]
Actually after updating my plugins it worked.

Sorry to bother.

Just wanna say I appreciate your plugin a lot and it is really helpful to me, thanks!
