### ISSUE TITLE
[feature] support scroll vertical

### ISSUE THREAD

**Issue by roachsinai** [sillybun/vim-repl#84]
REPL中无法回顾之前运行代码输出的结果。

比如，代码执行的结果高度超过了window的高度，就无法查看这个结果头几行的内容。

**Comment by sillybun** [comment]
可以事实上，因为terminal默认是insert模式，需要使用`<C-w><C-n>`进入normal模式能够看历史

或者可以使用我的键盘映射，

```
```

**Comment by roachsinai** [comment]
好的，感谢！

**Comment by shy00n** [comment]
@sillybun - I've been searching for this answer for a little too long!
So, for all of in English side, I will leave the translation of your answer below. 
Excellent & best for Python. I'm now using it with `sbt console` for Spark development!

> In fact, because the terminal is in insert mode by default, you need to use <C-w><C-n> to enter normal mode to see history
> Or you can use my keyboard mapping,
> ```
> tnoremap <C-n> <C-w>N
> tnoremap <ScrollWheelUp> <C-w>Nk
> tnoremap <ScrollWheelDown> <C-w>Nj
> ```
> In this way, the scroll wheel can also view history.
