### ISSUE TITLE
windows下用gvim设置虚拟环境的一些建议

### ISSUE THREAD

**Issue by StubbornVegeta** [sillybun/vim-repl#89]
我的配置win10+gvim8.2
---

我看到您在介绍里写到可以通过`g:repl_python_pre_launch_command`设置虚拟环境。

```vim
let g:repl_python_pre_launch_command = 'source /path_to_new_venv/bin/activate'
```

这好像只提供了linux下的设置方式。windows下要设置虚拟环境，我认为可以通过如下指令。

```vim
let g:repl_python_pre_launch_command = 'conda activate <environment name>'
```

这个方法是奏效的，但是当我退出`REPL`时，并不能像linux下完全退出，而是会退出到我的终端，我需要输入`exit`才能退出`REPL`。我认为这是因为`repl#REPLOpen`函数定义时，是如果发现含有虚拟环境则给`REPL_VIRTUAL_ENVIRONMENT`赋值，而调用`repl#REPLClose`函数关闭`REPL`时，如果发现存在`REPL_VIRTUAL_ENVIRONMENT`才继续退出。但`repl#REPLOpen`是按照linux系统下的虚拟环境检查的，所以需要添加windows下的检查方式。

因此我做了下面的改动：
在`vim-repl\autoload\repl.vim`找到`repl#StartWith(g:repl_python_pre_launch_command, 'source ')`这条语句，如下：
 ```vim
    if repl#StartWith(g:repl_python_pre_launch_command, 'source ')
        let g:REPL_VIRTUAL_ENVIRONMENT = repl#Strip(g:repl_python_pre_launch_command[strlen('source '):])
 ```

因为windows系统中并没有`source`，要激活虚拟环境，需要通过`conda activate <environment path>`语句。因此如果是windows系统，`source`处应该改为`conda`，如下：

 ```Vim
    if has('win32')
    	if repl#StartWith(g:repl_python_pre_launch_command, 'conda ')
    		let g:REPL_VIRTUAL_ENVIRONMENT = repl#Strip(g:repl_python_pre_launch_command[strlen('conda '):])
    	endif
    else
    	if repl#StartWith(g:repl_python_pre_launch_command, 'source ')
    		let g:REPL_VIRTUAL_ENVIRONMENT = repl#Strip(g:repl_python_pre_launch_command[strlen('source '):])
    	endif
    endif
 ```

这在我的gvim中是可以正常打开和关闭`REPL`窗口的。如果您觉得这个有用的话，可以考虑更新一下`repl.vim`文件。
另外我在windows系统中进入repl窗口的ipython时，默认会多打一行回车，我将`vim-repl\autoload\repl.vim`中`repl#REPLOpen`函数下的
```vim
if has('win32')
	let l:temp_return = "\r\n"
else
	let l:temp_return = "\n"
endif
```

修改为了：
```vim
if has('win32')
	let l:temp_return = "\r"
else
	let l:temp_return = "\n"
endif
```
之后就正常了

**Comment by sillybun** [comment]
我觉得您可以提供一个 PR

**Comment by sillybun** [comment]
感觉听起来很有用，但是我手头没有windows电脑，所以我比较难改。你可以提交Pull Request。

**Comment by demonlord1997** [comment]
> 感觉听起来很有用，但是我手头没有windows电脑，所以我比较难改。你可以提交Pull Request。

好的，我已经提交了PR。感谢阅读。
