### ISSUE TITLE
error occurred while sending codes to ipython

### ISSUE THREAD

**Issue by cyclony** [sillybun/vim-repl#9]
![image](https://user-images.githubusercontent.com/5020802/48331141-1eb73a80-e68a-11e8-865e-f164e0e0b790.png)

**Comment by cyclony** [comment]
this pic is better:
![image](https://user-images.githubusercontent.com/5020802/48331202-5625e700-e68a-11e8-9724-e152cfe724ee.png)

**Comment by sillybun** [comment]
This plugin needs pre-compiled.
Move to the plugin directory and run `./install.sh`

**Comment by cyclony** [comment]
hi errors come up during compiling:
![image](https://user-images.githubusercontent.com/5020802/48408768-1c7dda80-e775-11e8-871d-29ffbedfe577.png)
can u advise it? thx!

**Comment by misakisuna705** [comment]
我也遇到這個狀況
單行沒有問題
只有發送多行時，會顯示錯誤訊息

**Comment by sillybun** [comment]
I only test my code in `MacOS`. Maybe someday later, after I finish my final exam, I will try to fix the problem for Windows.

**Comment by sillybun** [comment]
The problem is I use C to do code indent analyze work. Currently you have to compile C code into `.so` file for the plugin to work correctly.

**Comment by David-Zeng** [comment]
![image](https://user-images.githubusercontent.com/1967197/56635221-3c141a00-66a8-11e9-85fd-fb75fa41aeab.png)

get error message:
`Error detected while processing function repl#SendChunkLines[1]..repl#SendLines[12]..repl#Sends:
line   10:
E117: Unknown function: AsyncCodeRun
`

**Comment by sillybun** [comment]
Now the plugin needs the support of another plugin `vim-async`

just put

```
Add Plug 'sillybun/vim-repl', {'do': './install.sh'} to .vimrc
Add Plug 'sillybun/vim-async', {'do': './install.sh'} to .vimrc
Add Plug 'sillybun/zytutil' to .vimrc
Run :PlugInstall
```

in your vimrc and install vim-async.

**Comment by sillybun** [comment]
@cyclony @misakisuna705 @David-Zeng Now this plugin support Windows! Sorry for the late update. Enjoy it.
